version: "3.7"

services:

  ontology-neo4j-test:
    build: ./test
    # Build the image with name and tag
    image: ontology-neo4j-test:1.0
    hostname: ontology-neo4j-test
    container_name: ontology-neo4j-test
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    ports:
      - "7455:7474"
      - "7658:7687"
    volumes:
      # Mount the neo4j configuration file to container
      - "./test/neo4j.conf:/usr/src/app/neo4j/conf/neo4j.conf"
      # Mount the neo4j sample database to container
      - "./test/ontology.db:/usr/src/app/neo4j/data/databases/ontology.db"
